source "http://gemcutter.org"
source "http://rubygems.org"
source "http://gems.github.com"

# NOTE: user ruby gems v1.5.3 or lower. Otherwise you will get errors like
# activesupport-2.3.5/lib/active_support/dependencies.rb:55: uninitialized constant ActiveSupport::Dependencies::Mutex

gem "builder", "~>2.1.2"

gem "bson_ext"
gem "i18n"
gem 'json_pure','1.6.1'
gem 'mongo_mapper',"0.8.6"
gem 'mongo','1.4.0'
gem 'plucky','0.3.8'
